"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import { Menu } from './Menu'

const inter = Inter({ subsets: ['latin'] })

 const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Menu />
        <div className="pl-2 pt-2">{children}</div>
        </body>
    </html>
  )
}
